"""Shared enums for the NDS project.

No enum in this file should directly imply a trade action.
"""
from __future__ import annotations
from enum import Enum

class Timeframe(str, Enum):
    M1="M1"; M5="M5"; M15="M15"; M30="M30"; H1="H1"; H4="H4"; D1="D1"

class Direction(int, Enum):
    BULLISH=1; BEARISH=-1; NEUTRAL=0

class ConfidenceLevel(str, Enum):
    CONFIRMED="CONFIRMED"; PROBABLE="PROBABLE"; UNCERTAIN="UNCERTAIN"; REQUIRES_REVIEW="REQUIRES_REVIEW"

class SourceValidationStatus(str, Enum):
    SOURCE_CONFIRMED="SOURCE_CONFIRMED"
    SOURCE_COMPATIBLE_INTERPRETATION="SOURCE_COMPATIBLE_INTERPRETATION"
    SOURCE_VALIDATION_REQUIRED="SOURCE_VALIDATION_REQUIRED"

class Point3Status(str, Enum):
    REJECTED="REJECTED"; BROKEN="BROKEN"; UNRESOLVED="UNRESOLVED"; NOT_APPLICABLE="NOT_APPLICABLE"

class Reference86Context(str, Enum):
    HOOK_CLOSURE="HOOK_CLOSURE"; CYCLE_CLOSURE="CYCLE_CLOSURE"; POINT_Z="POINT_Z"
    ND_NEAR_RETEST="ND_NEAR_RETEST"; TARGET_PROJECTION="TARGET_PROJECTION"
    FLAG_HOOK_VISUAL="FLAG_HOOK_VISUAL"; RALLY_RETRACE="RALLY_RETRACE"; NOT_APPLICABLE="NOT_APPLICABLE"

class SequenceState(str, Enum):
    WAIT_Z="WAIT_Z"; WAIT_N1="WAIT_N1"; WAIT_S1="WAIT_S1"; WAIT_N2="WAIT_N2"; WAIT_S2="WAIT_S2"
    WAIT_N3="WAIT_N3"; WAIT_S3="WAIT_S3"; CYCLE_COMPLETE="CYCLE_COMPLETE"; NEXT_CYCLE="NEXT_CYCLE"
    WAIT_POINT3_DECISION="WAIT_POINT3_DECISION"; WAIT_ND_CONFIRMATION="WAIT_ND_CONFIRMATION"; WAIT_FLAG="WAIT_FLAG"
    WAIT_MULTI_TIMEFRAME_CONFIRMATION="WAIT_MULTI_TIMEFRAME_CONFIRMATION"; WAIT_RISK_APPROVAL="WAIT_RISK_APPROVAL"

class CandidateStatus(str, Enum):
    CANDIDATE="CANDIDATE"; CONFIRMED_STRUCTURE="CONFIRMED_STRUCTURE"; INVALID_STRUCTURE="INVALID_STRUCTURE"
    NEEDS_REVIEW="NEEDS_REVIEW"; AGAINST_PARENT_PRESSURE="AGAINST_PARENT_PRESSURE"; INSUFFICIENT_DATA="INSUFFICIENT_DATA"

class HookType(str, Enum):
    TYPE_A="HOOK_TYPE_A"; TYPE_B="HOOK_TYPE_B"; UNKNOWN="HOOK_UNKNOWN"

class CyclePolarity(str, Enum):
    POSITIVE="POSITIVE_CYCLE"; NEGATIVE="NEGATIVE_CYCLE"; UNKNOWN="UNKNOWN_CYCLE"

class LabelType(str, Enum):
    Z="Z"; N1="N1"; S1="S1"; N2="N2"; S2="S2"; N3="N3"; S3="S3"
    CYCLE="CYCLE"; CYCLE_START="CYCLE_START"; CYCLE_END="CYCLE_END"; CYCLE_CLOSURE="CYCLE_CLOSURE"
    STRUCTURE_123="STRUCTURE_123"; HOOK_CLOSURE_123="HOOK_CLOSURE_123"; FRACTAL_LEG_123="FRACTAL_LEG_123"
    RALLY_123="RALLY_123"; TERMINAL_123="TERMINAL_123"; FLAG_TERMINATION_123="FLAG_TERMINATION_123"
    POINT_1="POINT_1"; POINT_2="POINT_2"; POINT_3="POINT_3"
    ND_CANDIDATE="ND_CANDIDATE"; ND_CONFIRMED="ND_CONFIRMED"; ND_INVALIDATED="ND_INVALIDATED"
    FLAG_CANDIDATE="FLAG_CANDIDATE"; FLAG_CONFIRMED="FLAG_CONFIRMED"; FLAG_INVALIDATED="FLAG_INVALIDATED"
    SMI="SMI"; BMI="BMI"; LVS="LVS"; F="F"
    HOOK_CANDIDATE="HOOK_CANDIDATE"; HOOK_TYPE_A="HOOK_TYPE_A"; HOOK_TYPE_B="HOOK_TYPE_B"; HOOK_UNKNOWN="HOOK_UNKNOWN"; HOOK_CLOSURE="HOOK_CLOSURE"
    RALLY="RALLY"; RALLY_SEGMENT_1="RALLY_SEGMENT_1"; RALLY_SEGMENT_2="RALLY_SEGMENT_2"; RALLY_SEGMENT_3="RALLY_SEGMENT_3"; RALLY_COMPLETION="RALLY_COMPLETION"; RALLY_EXHAUSTION="RALLY_EXHAUSTION"
    REFERENCE_86="REFERENCE_86"; HOOK_CLOSURE_86="HOOK_CLOSURE_86"; CYCLE_CLOSURE_86="CYCLE_CLOSURE_86"; POINT_Z_86="POINT_Z_86"; ND_RETEST_86="ND_RETEST_86"; TARGET_PROJECTION_86="TARGET_PROJECTION_86"; FLAG_HOOK_VISUAL_86="FLAG_HOOK_VISUAL_86"; RALLY_RETRACE_86="RALLY_RETRACE_86"
    PARENT_STRUCTURE="PARENT_STRUCTURE"; CHILD_STRUCTURE="CHILD_STRUCTURE"; HIGHER_TF_PRESSURE="HIGHER_TF_PRESSURE"; LOWER_TF_CONSTRUCTION="LOWER_TF_CONSTRUCTION"
